// Generated by gencpp from file chess_moves/movementstatusResponse.msg
// DO NOT EDIT!


#ifndef CHESS_MOVES_MESSAGE_MOVEMENTSTATUSRESPONSE_H
#define CHESS_MOVES_MESSAGE_MOVEMENTSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chess_moves
{
template <class ContainerAllocator>
struct movementstatusResponse_
{
  typedef movementstatusResponse_<ContainerAllocator> Type;

  movementstatusResponse_()
    {
    }
  movementstatusResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::chess_moves::movementstatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_moves::movementstatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct movementstatusResponse_

typedef ::chess_moves::movementstatusResponse_<std::allocator<void> > movementstatusResponse;

typedef boost::shared_ptr< ::chess_moves::movementstatusResponse > movementstatusResponsePtr;
typedef boost::shared_ptr< ::chess_moves::movementstatusResponse const> movementstatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_moves::movementstatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_moves::movementstatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace chess_moves

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_moves::movementstatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_moves::movementstatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_moves::movementstatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chess_moves::movementstatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_moves/movementstatusResponse";
  }

  static const char* value(const ::chess_moves::movementstatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::chess_moves::movementstatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct movementstatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_moves::movementstatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::chess_moves::movementstatusResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_MOVES_MESSAGE_MOVEMENTSTATUSRESPONSE_H
