// Generated by gencpp from file chess_moves/movementstatus.msg
// DO NOT EDIT!


#ifndef CHESS_MOVES_MESSAGE_MOVEMENTSTATUS_H
#define CHESS_MOVES_MESSAGE_MOVEMENTSTATUS_H

#include <ros/service_traits.h>


#include <chess_moves/movementstatusRequest.h>
#include <chess_moves/movementstatusResponse.h>


namespace chess_moves
{

struct movementstatus
{

typedef movementstatusRequest Request;
typedef movementstatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct movementstatus
} // namespace chess_moves


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chess_moves::movementstatus > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chess_moves::movementstatus&) { return value(); }
};

template<>
struct DataType< ::chess_moves::movementstatus > {
  static const char* value()
  {
    return "chess_moves/movementstatus";
  }

  static const char* value(const ::chess_moves::movementstatus&) { return value(); }
};


// service_traits::MD5Sum< ::chess_moves::movementstatusRequest> should match
// service_traits::MD5Sum< ::chess_moves::movementstatus >
template<>
struct MD5Sum< ::chess_moves::movementstatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chess_moves::movementstatus >::value();
  }
  static const char* value(const ::chess_moves::movementstatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_moves::movementstatusRequest> should match
// service_traits::DataType< ::chess_moves::movementstatus >
template<>
struct DataType< ::chess_moves::movementstatusRequest>
{
  static const char* value()
  {
    return DataType< ::chess_moves::movementstatus >::value();
  }
  static const char* value(const ::chess_moves::movementstatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chess_moves::movementstatusResponse> should match
// service_traits::MD5Sum< ::chess_moves::movementstatus >
template<>
struct MD5Sum< ::chess_moves::movementstatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chess_moves::movementstatus >::value();
  }
  static const char* value(const ::chess_moves::movementstatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_moves::movementstatusResponse> should match
// service_traits::DataType< ::chess_moves::movementstatus >
template<>
struct DataType< ::chess_moves::movementstatusResponse>
{
  static const char* value()
  {
    return DataType< ::chess_moves::movementstatus >::value();
  }
  static const char* value(const ::chess_moves::movementstatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHESS_MOVES_MESSAGE_MOVEMENTSTATUS_H
